### ISSUE TITLE
Maybe more example ,please?

### ISSUE THREAD

**Issue by xgz123** [containerd/console#26]
I'm still confusing about how to use it. I have tried the example. It didn't change the terminal size, just the output? 

~~~go
         current := console.Current()
	defer current.Reset()

	if err := current.SetRaw(); err != nil {
		fmt.Println(err)
	}
	ws, err := current.Size()
	if err != nil {
		fmt.Println(err)
	}
	ws.Height = ws.Height + 300
	ws.Width = ws.Width + 300
	current.Resize(ws)
	fmt.Println(123123)
	fmt.Println("'lorem ext ...asdfafjklas kljasfkjl '")
~~~

**Comment by mikebrow** [comment]
Did you try without the deferred Reset()? 

Some examples here:
https://github.com/containerd/console/blob/master/console_linux_test.go

Additional examples would be helpful, PRs welcome :)

**Comment by thaJeztah** [comment]
closing this ticket as it went stale
