### ISSUE TITLE
Cut a release

### ISSUE THREAD

**Issue by kolyshkin** [containerd/console#56]
It would be nice to have a release cut with #54 so that the users of
this package can remove pkg/errors from their vendoring.

**Comment by kolyshkin** [comment]
@AkihiroSuda @estesp very please 🙏🏻

**Comment by AkihiroSuda** [comment]
done

https://github.com/containerd/console/releases/tag/v1.0.3

**Comment by thaJeztah** [comment]
I see a new release was tagged; https://github.com/containerd/console/releases/tag/v1.0.3

**Comment by thaJeztah** [comment]
Ah, thank you browser cache (had this open in a tab, and it didn't refresh 😂🤣😂
