### ISSUE TITLE
New release request

### ISSUE THREAD

**Issue by andrewsun2898** [containerd/console#78]
Can we get a new release so we can get recent changes into vendored packages?

Thanks!

**Comment by andrewsun2898** [comment]
cc: @estesp @AkihiroSuda

**Comment by andrewsun2898** [comment]
Just to provide a bit more context, our project u-root (https://github.com/u-root/u-root) recently refactored part of our code base to use a library that uses containerd/console for terminal interactions. There has been issues with running the code on real hardware where the terminal gets mangled upon entering raw mode, a version with the fix in https://github.com/containerd/console/pull/77 would allow the feature to work.

**Comment by ldemailly** [comment]
Looks like it's done now - just need to be closed? https://github.com/containerd/console/releases/tag/v1.0.4
